# Generated by Django 5.0.2 on 2024-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='show_subgoals',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='hide_subgoals',
            field=models.BooleanField(default=False),
        ),
    ]
