version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./ascentflowhub_project:/app/ascentflowhub_project
    environment:
      - PG_DB_NAME=postgres
      - PG_USER=user
      - PG_PASSWORD=password
      - PG_HOST=db
    command: ["python3", "ascentflowhub_project/manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: docker.io/postgres:12-alpine
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # ensure the database gets created correctly
      # https://element-hq.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      # You may store the database tables in a local folder..
      - ./schemas:/var/lib/postgresql/data
      # .. or store them on some high performance storage for better results
      # - /path/to/ssd/storage:/var/lib/postgresql/data