# Generated by Django 5.0.2 on 2024-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_treegoalsmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='treegoalsmodel',
            name='slug_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
