# Generated by Django 5.0.2 on 2024-03-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_treegoalsmodel_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treegoalsmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treegoalsmodel',
            name='slug_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
