# Generated by Django 5.0.2 on 2024-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_treegoalsmodel_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treegoalsmodel',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='treegoalsmodel',
            name='slug_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
