# Generated by Django 5.0.2 on 2024-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_lifecategorymodel_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treegoalsmodel',
            name='weight',
            field=models.IntegerField(choices=[(3, 'Высокое'), (2, 'Среднее'), (1, 'Низкое')], default=1),
        ),
    ]
