# Generated by Django 5.0.2 on 2024-03-20 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_treegoalsmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='treegoalsmodel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
