# Generated by Django 5.0.2 on 2024-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_treegoalsmodel_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecategorymodel',
            name='percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
