# Generated by Django 5.0.2 on 2024-04-26 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_lifecategorymodel_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LifeCategoryModel',
            new_name='LifeCategory',
        ),
        migrations.RenameModel(
            old_name='TreeGoalsModel',
            new_name='TreeGoals',
        ),
    ]
