# Generated by Django 5.0.2 on 2024-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifespheremodel',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
