# Generated by Django 5.0.2 on 2024-02-24 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0002_alter_lifespheremodel_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LifeSphereModel',
            new_name='ProgressCircleModel',
        ),
    ]
