# Generated by Django 5.0.2 on 2024-02-24 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0003_rename_lifespheremodel_progresscirclemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgressCircleModel',
            new_name='LifeCategoryModel',
        ),
    ]
