# Generated by Django 5.0.2 on 2024-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0004_rename_progresscirclemodel_lifecategorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecategorymodel',
            name='latin_name',
        ),
        migrations.AddField(
            model_name='lifecategorymodel',
            name='slug_name',
            field=models.SlugField(blank=True, default='', max_length=25),
        ),
    ]
