# Generated by Django 5.0.2 on 2024-03-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0005_remove_lifecategorymodel_latin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeGoalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='AscentFlowHub_API.treegoalsmodel')),
            ],
        ),
    ]
