# Generated by Django 5.0.2 on 2024-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0008_treegoalsmodel_life_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='treegoalsmodel',
            name='weight',
            field=models.IntegerField(choices=[(1, 'Высокое'), (2, 'Среднее'), (3, 'Низкое')], default=1),
        ),
    ]
