# Generated by Django 5.0.2 on 2024-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0011_alter_treegoalsmodel_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treegoalsmodel',
            name='slug_name',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
