# Generated by Django 5.0.2 on 2024-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AscentFlowHub_API', '0014_alter_treegoalsmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecategorymodel',
            name='percent',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
